db:
  connector:
    insert:
      uri: dicom/instances
  service:
    url: http://10.201.8.58:8081/api/

file:
  server:
    path: /opt/fileserver

max:
  retries: 3
kafka:
  topic:
    receiver: dcm-recv-topic
    stgcmt: stgcmt-svc-topic
    email: email-svc-topic
    pathqa: pathqa-svc-topic
    scan-progress: scan-progress-topic

  bootstrap-servers: 10.201.8.56:9094
  producer:
    acks: all
    retries: 3
    batch-size: 16384
    linger-ms: 1
    buffer-memory: 33554432
    enable-idempotence: true
    compression-type: lz4
sharedfolder:
  password: 7;l2$3YH!O(N.Q1T1Btn
  servername: 10.201.8.11
  sharepath: Citius-Dev
  username: Citius-SVC@nsdev.local
  enableRemoteDirectoryWatcher: false
spring:
  application:
    name: eh-dicom-receiver
  main:
    banner-mode: log
  redis:
    host: 10.201.8.192
    port: 6379
    password: RedisUser@234
dicom:
  barcode:
    generation:
      enable: true
storescp:
  aetitle: EH_ENRICH
  aetitle.port: 2575
  bind: -b
  command: storescp
  directory: --directory
  storage:
    path: /opt/received

research:
  enable: true

visiopharm:
  url: http://10.201.8.34:81/AEPWEB/notification

gcp-config:
  pathqa-store-url: projects/prj-d-path-integration-cs1h/locations/us-central1/datasets/digital-pathology-dataset/dicomStores/digital-pathology-intermediate-dicom-store
  research-store-url: projects/prj-d-path-integration-cs1h/locations/us-central1/datasets/digital-pathology-dataset/dicomStores/dp-academic-dicom-store


